### ISSUE TITLE
SentinelServiceProvider Config problem

### ISSUE THREAD

**Issue by websemantics** [cartalyst/demo-api#2]
I'm getting this error right after composer install

{"error":{"type":"ErrorException","message":"Argument 1 passed to Cartalyst\Sentinel\Laravel\SentinelServiceProvider::configHitsLottery() must be of the type array, null given, called in \/Applications\/XAMPP\/xamppfiles\/htdocs\/demo-api\/vendor\/cartalyst\/sentinel\/src\/Laravel\/SentinelServiceProvider.php on line 414 and defined","file":"\/Applications\/XAMPP\/xamppfiles\/htdocs\/demo-api\/vendor\/cartalyst\/sentinel\/src\/Laravel\/SentinelServiceProvider.php","line":430}}{"error":{"type":"ErrorException","message":"Argument 1 passed to Cartalyst\Sentinel\Laravel\SentinelServiceProvider::configHitsLottery() must be of the type array, null given, called in \/Applications\/XAMPP\/xamppfiles\/htdocs\/demo-api\/vendor\/cartalyst\/sentinel\/src\/Laravel\/SentinelServiceProvider.php on line 414 and defined","file":"\/Applications\/XAMPP\/xamppfiles\/htdocs\/demo-api\/vendor\/cartalyst\/sentinel\/src\/Laravel\/SentinelServiceProvider.php","line":430}}MacBook-Pro-3:demo-api adnan$

It does seem to come from 

/Applications/XAMPP/xamppfiles/htdocs/demo-api/vendor/cartalyst/sentinel/src/Laravel/SentinelServiceProvider.php

Line: 396

Any thoughts?

Thank you

**Comment by suwardany** [comment]
Hello @websemantics I fixed these, pull in the changes and you should be good to go.

Let me know if you need any additional information.

**Comment by websemantics** [comment]
Thanks for that suwardany, .. problem fixed, .. 

one last issue, .. can't access the end-point http://localhost/demo-api/api/v1/places on my local, any pointers?

**Comment by suwardany** [comment]
No problem! Not sure how that is setup on your end, i'm testing it on a separate vhost so my url is `http://demo-api.dev/api/v1/places` and is working fine.

What happens when you hit that page?

**Comment by websemantics** [comment]
Object not found page, the only setting i did was the database config, .. am I missing something?

**Comment by suwardany** [comment]
Check out the steps here https://github.com/cartalyst/demo-api/blob/master/readme.md#installation .. need to migrate and seed sentinel and the db!

**Comment by websemantics** [comment]
Yes, followed all the steps, migrate, seed etc

**Comment by suwardany** [comment]
Did you run `composer install` after pulling the changes?

**Comment by websemantics** [comment]
I actually cloned the repo afresh, .. then ran composer

**Comment by suwardany** [comment]
Could you paste the error stacktrace on a gist or pastebin?

**Comment by websemantics** [comment]
It's not an error, but a 404

**Comment by suwardany** [comment]
maybe `http://localhost/demo-api/public/api/v1/places` ? It's related to your host setup, the browser isn't hitting the correct routes of the app

**Comment by websemantics** [comment]
That would give, 

Error in exception handler.

**Comment by suwardany** [comment]
That means the app is trying to write an exception and doesn't have the permissions to do so.

**Comment by websemantics** [comment]
I am checking the app/routes.php and nothing from those work including '/'

**Comment by websemantics** [comment]
Thanks though for your help, .. I'll do some debugging and report back

**Comment by suwardany** [comment]
You're welcome!

**Comment by websemantics** [comment]
Ok, found it, .. I had to run this 

''chmod 777 app/storage/*''

**Comment by vishalmote** [comment]
Hello,

I am facing the same issue : 

I have upgraded the laravel version 4.1 to 4.2.
I am using purchased version sentinel.
It is working properly in 4.1 but I have to upgarde the laravel version to 4.2 for other purpose but getting same kind of error please look attached screen shot.

Argument 1 passed to Cartalyst\Sentinel\Laravel\SentinelServiceProvider::configHitsLottery() must be of the type array, null given, called in /var/www/html/keurix50/web/vendor/cartalyst/sentinel/src/Laravel/SentinelServiceProvider.php on line 414 and defined

My composer.json is look like:
...
"repositories": [
        {
            "type": "composer",
            "url": "http://packages.cartalyst.com"
        }
    ],
    "require": {
        "laravel/framework": "4.2._",
        "cartalyst/sentinel": "1.0._",
        .
        .
        .
        .
       }
...

![screenshot from 2015-05-13 15 19 55](https://cloud.githubusercontent.com/assets/3690731/7607983/99766b3a-f983-11e4-9c8c-20871e6c1cef.png)

I dont know reason behind it.
composer install runs properly but when I try to visit a login page throghing above bug.

**Comment by brunogaspar** [comment]
You need to 're publish the Sentinel config file.

**Comment by levipeto** [comment]
php artisan vendor:publish
_then select_ 
[1 ] Provider: Cartalyst\Cart\Laravel\CartServiceProvider
